In [4]:
import numpy as np

In [15]:
#create numpy array of 1D,2D,3D
array_1d = np.array(["a", "b", "c"])
array_2d = np.array([["a", "b", "c"], [1, 2, 3]])
array_3d = np.array([[["a", "b", "c"],[1, 2, 3]],[["d", "e", "f"], [4, 5, 6]],[["i", "j", "k"], [7, 8, 9]]])


print ("array_1d =",array_1d, "\n")
print ("array_2d =",array_2d, "\n")
print ("array_3d =",array_3d)

array_1d = ['a' 'b' 'c'] 

array_2d = [['a' 'b' 'c']
 ['1' '2' '3']] 

array_3d = [[['a' 'b' 'c']
  ['1' '2' '3']]

 [['d' 'e' 'f']
  ['4' '5' '6']]

 [['i' 'j' 'k']
  ['7' '8' '9']]]


In [17]:
#create an array [2, 3, 10, 12, 7] and find the position of 10
array = np.array([2, 3, 10, 12, 7])
print(np.where(array == 10))

(array([2]),)


In [25]:
#create any random 1d array and sort it in both ascending and descending order
array_1 = np.array([2, 6, 4, 10, 9, 5])
print("ascending order", np.sort(array_1))
array_2 = np.copy(np.sort(array_1))
print("descending order", array_2[::-1])


ascending order [ 2  4  5  6  9 10]
descending order [10  9  6  5  4  2]


In [31]:
#create a 1d array and reshape it into 2d array
array_3 = np.array([3, 5, 7, 2, 1, 8])
print("1d array",array_3,"\n")
array_4 = array_3.reshape(2,3)
print("reshaped array \n", array_4)

1d array [3 5 7 2 1 8] 

reshaped array 
 [[3 5 7]
 [2 1 8]]


In [32]:
#create a 1d array and slice it from index [4:7]
array_5 = np.array([2, 4, 6, 7, 8, 9, 1, 0, 3, 5])
print("sliced array is \n", array_5[4:7])

sliced array is 
 [8 9 1]


In [34]:
#how many types of datatypes do we have in python

#string
#boolean
#variable
#float
#integer

In [41]:
#create a 1d array and then create a copy and view of it in diff variables

array_6 = np.array([1, 2, 3, 4, 5])
array_7 =  array_6.copy()
print("copy \n", array_7)
array_8 =  array_6.view()
print("view \n", array_8)


copy 
 [1 2 3 4 5]
view 
 [1 2 3 4 5]


In [ ]:
#create a 2d array and search for the index value of 7
array_9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.where(array_9 == 7))

(array([2]), array([0]))


In [42]:
#create a 1d array and access the data from [2:5]
array_10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array_10[2:5])

[3 4 5]


In [1]:
import numpy as np